#!/usr/bin/env rust-script
//! Mints a test token with a known key and prints the token + key as JSON.
//! Used by cross-language verification tests.
//!
//! Run: cargo test -p cloak-tokens -- --ignored --nocapture test_mint_cross_language_fixture
//! (This is actually run as a test in cloak-tokens, see below.)

// This file is documentation — the actual fixture is generated by:
// tests/cross-language/generate_fixture.sh
