use axum::http::StatusCode;

/// Severity levels for error classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    /// Informational — not a true error, but logged for visibility.
    Info,
    /// Expected error from user input or permissions.
    Warning,
    /// Unexpected failure requiring operator attention.
    Error,
    /// System-wide failure, likely cascading.
    Critical,
}

/// Static definition of a coded error.
#[derive(Debug, Clone)]
pub struct ErrorDef {
    pub code: &'static str,
    pub status: StatusCode,
    pub severity: Severity,
    pub retryable: bool,
    pub message: &'static str,
    pub suggestion: &'static str,
}

/// Lookup an error definition by code. O(n) scan over a small static array.
pub fn lookup(code: &str) -> Option<&'static ErrorDef> {
    CATALOG.iter().find(|e| e.code == code)
}

// ---------------------------------------------------------------------------
// The catalog
// ---------------------------------------------------------------------------

pub static CATALOG: &[ErrorDef] = &[
    // ── Cloak errors (CLOAK-xxx) ──────────────────────────────────────────
    ErrorDef {
        code: "CLOAK-001",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Critical,
        retryable: true,
        message: "Infisical secret store unavailable",
        suggestion: "Check Infisical connectivity and credentials. Secrets will serve from cache until restored.",
    },
    ErrorDef {
        code: "CLOAK-002",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Invalid authentication token",
        suggestion: "Re-authenticate to obtain a fresh token. The token may be corrupted or issued by an untrusted source.",
    },
    ErrorDef {
        code: "CLOAK-003",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Malformed token structure",
        suggestion: "Ensure the Authorization header contains a valid base64-encoded token with correct segment count.",
    },
    ErrorDef {
        code: "CLOAK-004",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Missing authentication token",
        suggestion: "Include an Authorization: Bearer <token> header with your request.",
    },
    ErrorDef {
        code: "CLOAK-005",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Invalid token signature",
        suggestion: "The token was signed with an unrecognized key. Re-register the service or re-issue the token.",
    },
    ErrorDef {
        code: "CLOAK-006",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Error,
        retryable: true,
        message: "No signing key available",
        suggestion: "The service has not completed registration with Cloak. Wait for registration or restart the service.",
    },
    ErrorDef {
        code: "CLOAK-007",
        status: StatusCode::FORBIDDEN,
        severity: Severity::Warning,
        retryable: false,
        message: "Insufficient permissions",
        suggestion: "The token does not grant the required operation class. Request a token with broader scopes.",
    },
    ErrorDef {
        code: "CLOAK-008",
        status: StatusCode::FORBIDDEN,
        severity: Severity::Warning,
        retryable: false,
        message: "Service not in token scope",
        suggestion: "The token does not include the target service in its scope. Re-issue with the correct service scope.",
    },
    ErrorDef {
        code: "CLOAK-009",
        status: StatusCode::NOT_FOUND,
        severity: Severity::Warning,
        retryable: false,
        message: "Service not registered",
        suggestion: "The target service has not registered with Cloak. Verify the service name and ensure it is running.",
    },
    ErrorDef {
        code: "CLOAK-010",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: true,
        message: "Service registration failed",
        suggestion: "Cloak could not register the service. Check Cloak logs for details and retry.",
    },
    ErrorDef {
        code: "CLOAK-011",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Critical,
        retryable: false,
        message: "Service halted by operator",
        suggestion: "An operator issued a halt command. The service will not process requests until restarted.",
    },
    ErrorDef {
        code: "CLOAK-012",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: false,
        message: "Configuration error",
        suggestion: "Check environment variables and configuration files for missing or invalid values.",
    },
    ErrorDef {
        code: "CLOAK-013",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: false,
        message: "Internal Cloak error",
        suggestion: "An unexpected error occurred inside Cloak. Check Cloak service logs for a stack trace.",
    },

    // ── Cortex errors (CTX-xxx) ───────────────────────────────────────────
    ErrorDef {
        code: "CTX-001",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Error,
        retryable: true,
        message: "Downstream service unavailable",
        suggestion: "The target service is not responding. Check its health endpoint and failure state.",
    },
    ErrorDef {
        code: "CTX-002",
        status: StatusCode::NOT_FOUND,
        severity: Severity::Warning,
        retryable: false,
        message: "Downstream service not found",
        suggestion: "No service with that name exists in the Cortex manifest. Check the URL path.",
    },
    ErrorDef {
        code: "CTX-003",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Critical,
        retryable: true,
        message: "Auth service (Cloak) unavailable",
        suggestion: "Cortex cannot reach Cloak for token verification. Check Cloak health and network connectivity.",
    },
    ErrorDef {
        code: "CTX-004",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Invalid token at proxy layer",
        suggestion: "The token failed verification at Cortex. Re-authenticate through Cloak.",
    },
    ErrorDef {
        code: "CTX-005",
        status: StatusCode::FORBIDDEN,
        severity: Severity::Warning,
        retryable: false,
        message: "Insufficient permissions at proxy layer",
        suggestion: "The token does not authorize this operation on the target service.",
    },
    ErrorDef {
        code: "CTX-006",
        status: StatusCode::GATEWAY_TIMEOUT,
        severity: Severity::Error,
        retryable: true,
        message: "Downstream request timed out",
        suggestion: "The downstream service did not respond within the configured timeout. Increase timeout_ms or investigate the service.",
    },
    ErrorDef {
        code: "CTX-007",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: true,
        message: "Proxy forwarding error",
        suggestion: "Cortex could not forward the request. Check downstream service connectivity.",
    },
    ErrorDef {
        code: "CTX-008",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: false,
        message: "Internal Cortex error",
        suggestion: "An unexpected error occurred inside Cortex. Check Cortex service logs.",
    },

    // ── Gateway errors (GW-xxx) ───────────────────────────────────────────
    ErrorDef {
        code: "GW-001",
        status: StatusCode::BAD_REQUEST,
        severity: Severity::Warning,
        retryable: false,
        message: "Bad request",
        suggestion: "Check the request body, query parameters, and content type.",
    },
    ErrorDef {
        code: "GW-002",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Unauthorized gateway request",
        suggestion: "Include a valid authentication token in the request.",
    },
    ErrorDef {
        code: "GW-003",
        status: StatusCode::NOT_FOUND,
        severity: Severity::Warning,
        retryable: false,
        message: "Route not found",
        suggestion: "The requested route key does not exist in the gateway configuration.",
    },
    ErrorDef {
        code: "GW-004",
        status: StatusCode::TOO_MANY_REQUESTS,
        severity: Severity::Warning,
        retryable: true,
        message: "Rate limited",
        suggestion: "Too many requests. Wait for the Retry-After period before retrying.",
    },
    ErrorDef {
        code: "GW-005",
        status: StatusCode::CONFLICT,
        severity: Severity::Info,
        retryable: false,
        message: "Duplicate request detected",
        suggestion: "This request was already processed. Use the original request ID to retrieve the result.",
    },
    ErrorDef {
        code: "GW-006",
        status: StatusCode::PAYMENT_REQUIRED,
        severity: Severity::Warning,
        retryable: false,
        message: "Budget exceeded",
        suggestion: "The caller's budget has been exhausted. Increase the budget allocation or wait for the next period.",
    },
    ErrorDef {
        code: "GW-007",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Error,
        retryable: true,
        message: "Gateway service unavailable",
        suggestion: "No healthy provider backends available. Check provider health and fallback configuration.",
    },
    ErrorDef {
        code: "GW-008",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: true,
        message: "Bad gateway response from provider",
        suggestion: "The upstream LLM provider returned an error. Check provider status pages.",
    },
    ErrorDef {
        code: "GW-009",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: false,
        message: "Internal gateway error",
        suggestion: "An unexpected error occurred inside the Gateway. Check Gateway service logs.",
    },

    // ── Provider errors (PROV-xxx) ────────────────────────────────────────
    ErrorDef {
        code: "PROV-001",
        status: StatusCode::GATEWAY_TIMEOUT,
        severity: Severity::Error,
        retryable: true,
        message: "Provider request timed out",
        suggestion: "The LLM provider did not respond in time. Retry or try an alternative provider.",
    },
    ErrorDef {
        code: "PROV-002",
        status: StatusCode::TOO_MANY_REQUESTS,
        severity: Severity::Warning,
        retryable: true,
        message: "Rate limited by provider",
        suggestion: "The provider is rate-limiting requests. Back off and retry after the indicated delay.",
    },
    ErrorDef {
        code: "PROV-003",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: true,
        message: "Provider server error",
        suggestion: "The provider returned a 5xx error. This is usually transient — retry after a brief delay.",
    },
    ErrorDef {
        code: "PROV-004",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: true,
        message: "Provider connection error",
        suggestion: "Could not connect to the provider. Check network connectivity and DNS resolution.",
    },
    ErrorDef {
        code: "PROV-005",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: false,
        message: "Invalid response from provider",
        suggestion: "The provider returned a response that could not be parsed. Check for API version changes.",
    },
    ErrorDef {
        code: "PROV-006",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Error,
        retryable: false,
        message: "Provider authentication failed",
        suggestion: "The API key for this provider is invalid or expired. Update the key in Infisical.",
    },
    ErrorDef {
        code: "PROV-007",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Critical,
        retryable: false,
        message: "Missing provider API key",
        suggestion: "The environment variable for this provider's API key is not set. Add it to the secret store.",
    },

    // ── Wheelhouse errors (WH-xxx) ───────────────────────────────────────
    ErrorDef {
        code: "WH-001",
        status: StatusCode::BAD_REQUEST,
        severity: Severity::Warning,
        retryable: false,
        message: "Task validation: missing required field",
        suggestion: "Include all required fields in the task definition. Check the task schema.",
    },
    ErrorDef {
        code: "WH-002",
        status: StatusCode::BAD_REQUEST,
        severity: Severity::Warning,
        retryable: false,
        message: "Task validation: invalid value",
        suggestion: "The provided value does not meet validation constraints. Check allowed ranges and formats.",
    },
    ErrorDef {
        code: "WH-003",
        status: StatusCode::NOT_FOUND,
        severity: Severity::Warning,
        retryable: false,
        message: "Agent not found",
        suggestion: "The specified agent ID does not exist in the pool. It may have been reclaimed.",
    },
    ErrorDef {
        code: "WH-004",
        status: StatusCode::SERVICE_UNAVAILABLE,
        severity: Severity::Error,
        retryable: true,
        message: "Agent pool full",
        suggestion: "All agent slots are occupied. Wait for an agent to complete or increase pool capacity.",
    },
    ErrorDef {
        code: "WH-005",
        status: StatusCode::CONFLICT,
        severity: Severity::Warning,
        retryable: false,
        message: "Invalid agent state transition",
        suggestion: "The agent cannot move from its current state to the requested state. Check the lifecycle FSM.",
    },
    ErrorDef {
        code: "WH-006",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: true,
        message: "Task creation failed in orchestrator",
        suggestion: "The orchestrator could not create the task. Check Wheelhouse logs for details.",
    },
    ErrorDef {
        code: "WH-007",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: true,
        message: "Agent spawn failed",
        suggestion: "Could not spawn a new agent instance. Check resource limits and pool state.",
    },
    ErrorDef {
        code: "WH-008",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: false,
        message: "Agent assignment failed",
        suggestion: "Could not assign an agent to the task. The agent may have been reclaimed between selection and assignment.",
    },
    ErrorDef {
        code: "WH-009",
        status: StatusCode::INTERNAL_SERVER_ERROR,
        severity: Severity::Error,
        retryable: false,
        message: "Agent fate application failed",
        suggestion: "Could not apply the fate (retire/reclaim) to the agent. Check agent state.",
    },
    ErrorDef {
        code: "WH-010",
        status: StatusCode::NOT_FOUND,
        severity: Severity::Warning,
        retryable: false,
        message: "Task not found",
        suggestion: "The task at the given index does not exist. It may have been completed or cancelled.",
    },

    // ── Analog Communications errors (AC-xxx) ────────────────────────────
    ErrorDef {
        code: "AC-001",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: true,
        message: "Dispatch network error",
        suggestion: "Could not reach the downstream dispatch target. Check network connectivity.",
    },
    ErrorDef {
        code: "AC-002",
        status: StatusCode::BAD_GATEWAY,
        severity: Severity::Error,
        retryable: true,
        message: "Downstream service error during dispatch",
        suggestion: "The downstream service returned an error. Check the service status and retry.",
    },
    ErrorDef {
        code: "AC-003",
        status: StatusCode::UNAUTHORIZED,
        severity: Severity::Warning,
        retryable: false,
        message: "Unauthorized SMS sender",
        suggestion: "The sender phone number is not in the allowlist. Add it to authorized senders.",
    },
    ErrorDef {
        code: "AC-004",
        status: StatusCode::BAD_REQUEST,
        severity: Severity::Warning,
        retryable: false,
        message: "Invalid sender number (not E.164)",
        suggestion: "The sender number must be in E.164 format (e.g. +15551234567).",
    },
    ErrorDef {
        code: "AC-005",
        status: StatusCode::BAD_REQUEST,
        severity: Severity::Warning,
        retryable: false,
        message: "Empty message body",
        suggestion: "The inbound SMS body is empty. This may indicate a media-only message.",
    },
    ErrorDef {
        code: "AC-006",
        status: StatusCode::BAD_REQUEST,
        severity: Severity::Warning,
        retryable: false,
        message: "Message too long",
        suggestion: "The message exceeds the maximum allowed length. Truncate or split the message.",
    },
];
